apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-claim
  labels:
    app: auth-mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv-name: auth-mongo-volume
