apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-mongo-volume
  labels:
    type: local
    app: auth-mongo
    pv-name: auth-mongo-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/auth-mongodb
