apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
    - ../questify-frontend/infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: questify/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: questify/course-mgmt
      context: course_management
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: questify/course-learning
      context: course_learning
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: questify/code-problem
      context: code_problem
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: questify/admin
      context: admin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: questify/client
      context: ../questify-frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.tsx'
            dest: .
          - src: 'src/**/*.ts'
            dest: .
          - src: 'public/**/*'
            dest: .
