apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-postgres-volume
  labels:
    type: local
    app: admin-postgres
    pv-name: admin-postgres-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: admin-postgres-volume-claim
  hostPath:
    path: /data/admin-postgresql-fresh
