name: Next.js Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Next.js build
        run: |
          echo "Running Next.js build check..."
          npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_IMG_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_IMG_FIREBASE_API_KEY }}
          NEXT_PUBLIC_IMG_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_IMG_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_IMG_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_IMG_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_IMG_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_IMG_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_IMG_FIREBASE_MESSAGE_SENDER_ID: ${{ secrets.NEXT_PUBLIC_IMG_FIREBASE_MESSAGE_SENDER_ID }}
          NEXT_PUBLIC_IMG_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_IMG_FIREBASE_APP_ID }}

      - name: Provide instructions if check fails
        if: ${{ failure() }}
        run: |
          echo "::error::❌ Next.js build failed!"
          echo "::error::Bro please fix the build issues before pushing again."
          exit 1
