apiVersion: v1
kind: Secret
metadata:
  name: admin-postgres-secret
  labels:
    app: admin-postgres
type: Opaque
stringData:
  POSTGRES_DB: admin_ps_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: AdminSecurePassword
