apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: questify-tls
  namespace: default
spec:
  secretName: questify-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - www.questify.site
