apiVersion: v1
kind: ConfigMap
metadata:
  name: code-problem-postgres-init
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      ALTER USER postgres WITH PASSWORD '$POSTGRES_PASSWORD';
    EOSQL
