apiVersion: v1
kind: PersistentVolume
metadata:
  name: course-mgmt-postgres-volume
  labels:
    type: local
    app: course-mgmt-postgres
    pv-name: course-mgmt-postgres-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/course-mgmt-postgresql
#
