export enum Subjects {
  UserCreated = 'user:created',
  UserUpdated = 'user:updated',
  CourseCreated = 'course:created',
  CourseUpdated = 'course:updated',
  IslandCreated = 'island:created',
  IslandUpdated = 'island:updated',
  LevelCreated = 'level:created',
  LevelUpdated = 'level:updated',
  AttemptCreated = 'attempt:created',
  AttemptUpdated = 'attempt:updated',
  IslandTemplateCreated = 'islandtemplate:created',
  IslandTemplateUpdated = 'islandtemplate:updated',
  PrerequisiteIslandCreated = 'prerequisiteisland:created',
  PrerequisiteIslandDeleted = 'prerequisiteisland:deleted',
  UserCourseCreated = 'usercourse:created',
  UserCourseUpdated = 'usercourse:updated',
  UserCourseInventoryCreation = 'user-course-inventory-creation',
  ItemTemplateCreated = 'itemtemplate:created',
  ItemTemplateUpdated = 'itemtemplate:updated',
  ItemTemplateDeleted = 'itemtemplate:deleted',
  CourseItemTemplateCreated = 'courseitemtemplate:created',
  CourseItemTemplateUpdated = 'courseitemtemplate:updated',
  ChallengeCreated = 'challenge:created',
  ChallengeUpdated = 'challenge:updated',
  SlideCreated = 'slide:created',
  SlideUpdated = 'slide:updated',
}
