apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-postgres-volume-claim
  labels:
    app: admin-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      pv-name: admin-postgres-volume
